name: 'Desktop icon Transform'
description: 'Modifies icons so they match format conventions for desktop'

inputs:
  files:
    description: 'Glob pattern of files to transform'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        INPUT_FILES: ${{ inputs.files }}
      run: '"${{ github.action_path }}/../../node_modules/.bin/tsx" "${{ github.action_path }}/index.ts"'
