name: 'Icon Transform'
description: 'Modifies icons so they follow the same format'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: '"${{ github.action_path }}/../../node_modules/.bin/tsx" "${{ github.action_path }}/index.ts"'
